# Generated by Django 4.2.11 on 2024-04-13 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_visualizations', '0003_alter_task_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='datetime',
            new_name='uploaded_at',
        ),
    ]
