# Generated by Django 4.2.11 on 2024-04-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_visualizations', '0005_task_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(upload_to='file_csv'),
        ),
        migrations.AlterField(
            model_name='task',
            name='label',
            field=models.CharField(max_length=50),
        ),
    ]
